### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by haaddii** [0xgkd/awvs#13]
```bash
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='erp.acunetix.com', port=443): Max retries exceeded with url: /TargetManagement/Targets/GetTargets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1b377fb740>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by 0xgkd** [comment]
> ```shell
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='erp.acunetix.com', port=443): Max retries exceeded with url: /TargetManagement/Targets/GetTargets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1b377fb740>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ```

容器使用过程中这个域名erp.acunetix.com日志报错是正常的，不影响使用

**Comment by haaddii** [comment]
那可能连不上的问题不是这里。

```
2024-10-25 12:59:12 
2024-10-25 12:59:12 Traceback (most recent call last):
2024-10-25 12:59:12   File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
2024-10-25 12:59:12   File "gevent/baseserver.py", line 34, in _handle_and_close_when_done
2024-10-25 12:59:12   File "gevent/server.py", line 209, in wrap_socket_and_handle
2024-10-25 12:59:12   File "gevent/ssl.py", line 120, in wrap_socket
2024-10-25 12:59:12   File "gevent/ssl.py", line 349, in __init__
2024-10-25 12:59:12   File "gevent/ssl.py", line 724, in do_handshake
2024-10-25 12:59:12 ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:1000)
2024-10-25 12:59:12 2024-10-25T03:59:12Z <Greenlet at 0x7f953db382c0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7f953e558b4)> failed with SSLError
```
这个问题请问该怎么处理？
更新了docker之后就启动不了这个image了……

**Comment by haaddii** [comment]
Full log:
```bash
2024-10-25 13:06:23 attempting to stop previous message brokers
2024-10-25 13:06:23 attempting to stop previous database
2024-10-25 13:06:23 attempting to start the db
2024-10-25 13:06:23 waiting for server to start....2024-10-25 04:06:23.207 UTC [37] LOG:  starting PostgreSQL 13.14 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit
2024-10-25 13:06:23 2024-10-25 04:06:23.207 UTC [37] LOG:  listening on IPv6 address "::1", port 35432
2024-10-25 13:06:23 2024-10-25 04:06:23.207 UTC [37] LOG:  listening on IPv4 address "127.0.0.1", port 35432
2024-10-25 13:06:23 2024-10-25 04:06:23.210 UTC [37] LOG:  listening on Unix socket "/tmp/.s.PGSQL.35432"
2024-10-25 13:06:23 2024-10-25 04:06:23.212 UTC [38] LOG:  database system was shut down at 2024-09-09 03:03:32 UTC
2024-10-25 13:06:23 2024-10-25 04:06:23.216 UTC [37] LOG:  database system is ready to accept connections
2024-10-25 13:06:23  done
2024-10-25 13:06:23 server started
2024-10-25 13:06:23 attempting to start the message broker
2024-10-25 13:06:23 pg_ctl: PID file "/home/acunetix/.acunetix/db/postmaster.pid" does not exist
2024-10-25 13:06:23 Is server running?
2024-10-25 13:06:23 chmod: cannot access '/home/acunetix/.acunetix/v_240828144/broker/server.conf': No such file or directory
2024-10-25 13:06:23 sed: can't read /home/acunetix/.acunetix/v_240828144/broker/server.conf: No such file or directory
2024-10-25 13:06:23 sed: can't read /home/acunetix/.acunetix/v_240828144/broker/server.conf: No such file or directory
2024-10-25 13:06:23 sed: can't read /home/acunetix/.acunetix/v_240828144/broker/server.conf: No such file or directory
2024-10-25 13:06:23 sed: can't read /home/acunetix/.acunetix/v_240828144/broker/server.conf: No such file or directory
2024-10-25 13:06:23 sed: can't read /home/acunetix/.acunetix/v_240828144/broker/server.conf: No such file or directory
2024-10-25 13:06:23 nats-server: open /home/acunetix/.acunetix/v_240828144/broker/server.conf: no such file or directory
2024-10-25 13:06:26 attempting to stop previous integrations services
2024-10-25 13:06:26 attempting to start the backend
2024-10-25 13:06:27 2024-10-25 04:06:27,083: WARNING application.init unhandled config key wvs.temp_dir, ignoring
2024-10-25 13:06:27 2024-10-25 04:06:27,083: WARNING application.init invalid config entry , ignoring
2024-10-25 13:06:27 2024-10-25 04:06:27,083: WARNING application.init unhandled config key aes_encryption_key, ignoring
2024-10-25 13:06:27 2024-10-25 04:06:27,083: WARNING application.init invalid config entry , ignoring
2024-10-25 13:06:27 2024-10-25 04:06:27,084: INFO helpers.application.util base_app_storage is set, using it
2024-10-25 13:06:27 2024-10-25 04:06:27,084: INFO helpers.application.util base_user_storage is set, using it
2024-10-25 13:06:27 2024-10-25 04:06:27,085: INFO helpers.application.util Creating user_storage.updates directory: /home/acunetix/.acunetix/data/updates
2024-10-25 13:06:27 2024-10-25 04:06:27,085: INFO helpers.application.util Creating user_storage.lsr_logs directory: /home/acunetix/.acunetix/data/lsr_logs
2024-10-25 13:06:27 2024-10-25 04:06:27,086: INFO helpers.application.util Storage root: /home/acunetix/.acunetix
2024-10-25 13:06:27 2024-10-25 04:06:27,090: INFO application.init Checking database connection...
2024-10-25 13:06:27 2024-10-25 04:06:27,142: INFO application.init Database connection OK. Found database version: 240800
2024-10-25 13:06:27 2024-10-25 04:06:27,163: INFO application.init Database version: 240800
2024-10-25 13:06:27 2024-10-25 04:06:27,163: INFO application.init Running database update script: update_database.sql
2024-10-25 13:06:27 2024-10-25 04:06:27,221: INFO application.init Database version: 240800
2024-10-25 13:06:27 2024-10-25 04:06:27,221: INFO application.init Running database update script: static_data.sql
2024-10-25 13:06:27 2024-10-25 04:06:27,321: INFO application.init Database maintenance done
2024-10-25 13:06:27 2024-10-25 04:06:27,323: ERROR root chown failed with [Errno 1] Operation not permitted: '/home/acunetix/.acunetix/data/license/license_info.json'
2024-10-25 13:06:27 Traceback (most recent call last):
2024-10-25 13:06:27   File "helpers/application/access_rights.py", line 12, in chmod
2024-10-25 13:06:27 PermissionError: [Errno 1] Operation not permitted: '/home/acunetix/.acunetix/data/license/license_info.json'
2024-10-25 13:06:27 2024-10-25 04:06:27,334: INFO application.init New installation ID: e7ae7747f284554b035dabafaba348e1
2024-10-25 13:06:27 2024-10-25 04:06:27,418: WARNING helpers.licensing ### activation returned 1
2024-10-25 13:06:28 2024-10-25 04:06:28,473: INFO service.master SSL OpenSSL 3.3.1 4 Jun 2024
2024-10-25 13:06:28 2024-10-25 04:06:28,675: INFO service.master creating system proxy callback
2024-10-25 13:06:28 2024-10-25 04:06:28,678: INFO helpers.application.util Starting app, version: 24.8.240828144 [Linux] (gev:24.2.1)
2024-10-25 13:06:28 2024-10-25 04:06:28,680: INFO service.master Database version: 240800
2024-10-25 13:06:28 2024-10-25 04:06:28,681: INFO service.master starting backend
2024-10-25 13:06:28 2024-10-25 04:06:28,681: INFO service.master getting license
2024-10-25 13:06:29 2024-10-25 04:06:29,534: INFO helpers.application.util adjusting ca bundle...
2024-10-25 13:06:29 2024-10-25 04:06:29,534: INFO helpers.application.util settings ca value: None
2024-10-25 13:06:29 2024-10-25 04:06:29,553: INFO helpers.security_blob.loader attempting to download the latest blob
2024-10-25 13:06:30 2024-10-25 04:06:30,684: INFO helpers.security_blob.loader Loaded the security blob: /home/acunetix/.acunetix/data/security/security_240828112.bin
2024-10-25 13:06:31 2024-10-25 04:06:31,539: INFO helpers.security_blob.loader BlobLoader initialized
2024-10-25 13:06:31 2024-10-25 04:06:31,540: INFO service.master creating system updater
2024-10-25 13:06:31 2024-10-25 04:06:31,583: INFO service.master registering session handlers
2024-10-25 13:06:31 2024-10-25 04:06:31,585: INFO service.master status api on https://localhost:3443/status/v1/
2024-10-25 13:06:31 2024-10-25 04:06:31,587: INFO service.master Initialization of messaging broker and streams...
2024-10-25 13:06:31 2024-10-25 04:06:31,587: WARNING service.master Unexpected error happened during messaging streams initialization (e.g. server is not running): Couldn't find the nats-server.conf file at /home/acunetix/.acunetix/v_240828144/scanner/../broker/nats-server.conf
2024-10-25 13:06:31 2024-10-25 04:06:31,587: WARNING service.master Messaging client initialization will be skipped and events will not be published.
2024-10-25 13:06:31 2024-10-25 04:06:31,589: WARNING service.master Subscription in message broker was not successfully done: 'NoneType' object has no attribute 'subscribe_for_message'
2024-10-25 13:06:31 2024-10-25 04:06:31,589: INFO service.master creating the broker
2024-10-25 13:06:31 2024-10-25 04:06:31,589: INFO service.master starting the broker
2024-10-25 13:06:31 2024-10-25 04:06:31,590: INFO service.master starting the db_based_scheduler
2024-10-25 13:06:31 2024-10-25 04:06:31,608: INFO service.master creating the http server
2024-10-25 13:06:31 2024-10-25 04:06:31,731: INFO server.routers.api.routes checking _routes:
2024-10-25 13:06:31 2024-10-25 04:06:31,740: INFO server.routers.api.routes checking _routes:
2024-10-25 13:06:31 2024-10-25 04:06:31,749: INFO server.routers.api.routes checking _routes:
2024-10-25 13:06:31 2024-10-25 04:06:31,750: INFO server.static.router creating route for /home/acunetix/.acunetix/v_240828144/vue-ui (base path /app)
2024-10-25 13:06:31 2024-10-25 04:06:31,785: INFO server.static.router indexed 505 files
2024-10-25 13:06:31 2024-10-25 04:06:31,786: INFO server.static.router skipped 0 files
2024-10-25 13:06:31 2024-10-25 04:06:31,786: INFO server.static.router creating route for /home/acunetix/.acunetix/v_240828144/ui (base path None)
2024-10-25 13:06:31 2024-10-25 04:06:31,798: INFO server.static.router indexed 130 files
2024-10-25 13:06:31 2024-10-25 04:06:31,798: INFO server.static.router skipped 0 files
2024-10-25 13:06:31 2024-10-25 04:06:31,799: INFO server.application server application initialized
2024-10-25 13:06:31 2024-10-25 04:06:31,971: INFO service.master starting the http server
2024-10-25 13:06:31 2024-10-25 04:06:31,975: INFO service.master starting the reporter
2024-10-25 13:06:31 2024-10-25 04:06:31,976: INFO service.master reporter worker started
2024-10-25 13:06:31 2024-10-25 04:06:31,976: INFO reporter wvs_basedir /home/acunetix/.acunetix/v_240828144/scanner
2024-10-25 13:06:31 2024-10-25 04:06:31,976: INFO reporter searching for pdf generator...
2024-10-25 13:06:31 2024-10-25 04:06:31,976: INFO reporter trying /home/acunetix/.acunetix/v_240828144/scanner/pdf
2024-10-25 13:06:31 2024-10-25 04:06:31,977: INFO reporter trying /home/acunetix/.acunetix/v_240828144/scanner/pdf.exe
2024-10-25 13:06:31 2024-10-25 04:06:31,977: INFO reporter trying /home/acunetix/.acunetix/v_240828144/scanner/node
2024-10-25 13:06:31 2024-10-25 04:06:31,977: INFO reporter pdf_converter=['/home/acunetix/.acunetix/v_240828144/scanner/node', 'pdf']
2024-10-25 13:06:31 2024-10-25 04:06:31,978: INFO service.master starting the system updater
2024-10-25 13:06:31 2024-10-25 04:06:31,978: INFO helpers.updater update thread started
2024-10-25 13:06:31 2024-10-25 04:06:31,979: INFO service.master starting the acumonitor thread
2024-10-25 13:06:31 2024-10-25 04:06:31,980: INFO service.master starting the mailer thread
2024-10-25 13:06:31 2024-10-25 04:06:31,981: INFO service.master starting lsr worker thread
2024-10-25 13:06:31 2024-10-25 04:06:31,983: INFO service.master worker_checker started
2024-10-25 13:06:32 2024-10-25 04:06:32,051: INFO xfqdn start fqdn processing for 986ad8c0a5b3df4d7028d5f3c06e936c
2024-10-25 13:06:32 2024-10-25 04:06:32,074: INFO helpers.licensing re-activating
2024-10-25 13:06:32 2024-10-25 04:06:32,549: INFO application.init Vtypes updated in 1.001655436999954 seconds
2024-10-25 13:06:32 2024-10-25 04:06:32,712: WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f960c170d70>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/DeleteTargets
2024-10-25 13:06:32 2024-10-25 04:06:32,714: WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9609c37740>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/DeleteTargets
2024-10-25 13:06:32 2024-10-25 04:06:32,716: WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9609dca750>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/DeleteTargets
2024-10-25 13:06:32 2024-10-25 04:06:32,717: ERROR xfqdn migration request failed with HTTPSConnectionPool(host='erp.acunetix.com', port=443): Max retries exceeded with url: /TargetManagement/Targets/DeleteTargets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9609b0c6e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-10-25 13:06:32 Traceback (most recent call last):
2024-10-25 13:06:32   File "urllib3/connection.py", line 196, in _new_conn
2024-10-25 13:06:32   File "urllib3/util/connection.py", line 85, in create_connection
2024-10-25 13:06:32   File "urllib3/util/connection.py", line 73, in create_connection
2024-10-25 13:06:32   File "gevent/_socketcommon.py", line 590, in connect
2024-10-25 13:06:32   File "gevent/_socketcommon.py", line 634, in _internal_connect
2024-10-25 13:06:32 ConnectionRefusedError: [Errno 111] Connection refused
2024-10-25 13:06:32 
2024-10-25 13:06:32 The above exception was the direct cause of the following exception:
2024-10-25 13:06:32 
2024-10-25 13:06:32 Traceback (most recent call last):
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 789, in urlopen
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 490, in _make_request
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 466, in _make_request
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 1095, in _validate_conn
2024-10-25 13:06:32   File "urllib3/connection.py", line 615, in connect
2024-10-25 13:06:32   File "urllib3/connection.py", line 211, in _new_conn
2024-10-25 13:06:32 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9609b0c6e0>: Failed to establish a new connection: [Errno 111] Connection refused
2024-10-25 13:06:32 
2024-10-25 13:06:32 The above exception was the direct cause of the following exception:
2024-10-25 13:06:32 
2024-10-25 13:06:32 Traceback (most recent call last):
2024-10-25 13:06:32   File "helpers/licensing/targets/fqdn.py", line 1073, in process_all_fqdn_by_owner_and_type
2024-10-25 13:06:32   File "helpers/licensing/targets/service.py", line 214, in uninstall
2024-10-25 13:06:32   File "helpers/licensing/targets/service.py", line 195, in do_request
2024-10-25 13:06:32   File "urllib3/_request_methods.py", line 144, in request
2024-10-25 13:06:32   File "urllib3/_request_methods.py", line 279, in request_encode_body
2024-10-25 13:06:32   File "urllib3/poolmanager.py", line 443, in urlopen
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 873, in urlopen
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 873, in urlopen
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 873, in urlopen
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 843, in urlopen
2024-10-25 13:06:32   File "urllib3/util/retry.py", line 519, in increment
2024-10-25 13:06:32 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='erp.acunetix.com', port=443): Max retries exceeded with url: /TargetManagement/Targets/DeleteTargets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9609b0c6e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-10-25 13:06:32 2024-10-25 04:06:32,722: WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9609b0c650>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/GetTargets
2024-10-25 13:06:32 2024-10-25 04:06:32,723: WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9609b0c380>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/GetTargets
2024-10-25 13:06:32 2024-10-25 04:06:32,724: WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9609b0c620>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/GetTargets
2024-10-25 13:06:32 2024-10-25 04:06:32,725: ERROR xfqdn error reaching target management service HTTPSConnectionPool(host='erp.acunetix.com', port=443): Max retries exceeded with url: /TargetManagement/Targets/GetTargets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9609b0ca70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-10-25 13:06:32 Traceback (most recent call last):
2024-10-25 13:06:32   File "urllib3/connection.py", line 196, in _new_conn
2024-10-25 13:06:32   File "urllib3/util/connection.py", line 85, in create_connection
2024-10-25 13:06:32   File "urllib3/util/connection.py", line 73, in create_connection
2024-10-25 13:06:32   File "gevent/_socketcommon.py", line 590, in connect
2024-10-25 13:06:32   File "gevent/_socketcommon.py", line 634, in _internal_connect
2024-10-25 13:06:32 ConnectionRefusedError: [Errno 111] Connection refused
2024-10-25 13:06:32 
2024-10-25 13:06:32 The above exception was the direct cause of the following exception:
2024-10-25 13:06:32 
2024-10-25 13:06:32 Traceback (most recent call last):
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 789, in urlopen
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 490, in _make_request
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 466, in _make_request
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 1095, in _validate_conn
2024-10-25 13:06:32   File "urllib3/connection.py", line 615, in connect
2024-10-25 13:06:32   File "urllib3/connection.py", line 211, in _new_conn
2024-10-25 13:06:32 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9609b0ca70>: Failed to establish a new connection: [Errno 111] Connection refused
2024-10-25 13:06:32 
2024-10-25 13:06:32 The above exception was the direct cause of the following exception:
2024-10-25 13:06:32 
2024-10-25 13:06:32 Traceback (most recent call last):
2024-10-25 13:06:32   File "helpers/licensing/targets/fqdn.py", line 1101, in process_all_fqdn_by_owner_and_type
2024-10-25 13:06:32   File "helpers/licensing/targets/service.py", line 259, in get_targets
2024-10-25 13:06:32   File "helpers/licensing/targets/service.py", line 195, in do_request
2024-10-25 13:06:32   File "urllib3/_request_methods.py", line 144, in request
2024-10-25 13:06:32   File "urllib3/_request_methods.py", line 279, in request_encode_body
2024-10-25 13:06:32   File "urllib3/poolmanager.py", line 443, in urlopen
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 873, in urlopen
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 873, in urlopen
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 873, in urlopen
2024-10-25 13:06:32   File "urllib3/connectionpool.py", line 843, in urlopen
2024-10-25 13:06:32   File "urllib3/util/retry.py", line 519, in increment
2024-10-25 13:06:32 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='erp.acunetix.com', port=443): Max retries exceeded with url: /TargetManagement/Targets/GetTargets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9609b0ca70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-10-25 13:06:32 2024-10-25 04:06:32,727: INFO xfqdn end fqdn processing for 986ad8c0a5b3df4d7028d5f3c06e936c
2024-10-25 13:06:32 2024-10-25 04:06:32,985: INFO service.master system init completed.
2024-10-25 13:06:32 2024-10-25 04:06:32,985: INFO service.master Platform: Linux,Ubuntu 18.04.6 LTS,6.10.4-linuxkit,2.27
```

**Comment by 0xgkd** [comment]
> 那可能连不上的问题不是这里。
> 
> ```
> 2024-10-25 12:59:12 
> 2024-10-25 12:59:12 Traceback (most recent call last):
> 2024-10-25 12:59:12   File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
> 2024-10-25 12:59:12   File "gevent/baseserver.py", line 34, in _handle_and_close_when_done
> 2024-10-25 12:59:12   File "gevent/server.py", line 209, in wrap_socket_and_handle
> 2024-10-25 12:59:12   File "gevent/ssl.py", line 120, in wrap_socket
> 2024-10-25 12:59:12   File "gevent/ssl.py", line 349, in __init__
> 2024-10-25 12:59:12   File "gevent/ssl.py", line 724, in do_handshake
> 2024-10-25 12:59:12 ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:1000)
> 2024-10-25 12:59:12 2024-10-25T03:59:12Z <Greenlet at 0x7f953db382c0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7f953e558b4)> failed with SSLError
> ```
> 
> 这个问题请问该怎么处理？ 更新了docker之后启动这个image就一直连不上了……

容器删掉重新创建，注意映射端口别冲突
