### ISSUE TITLE
Docker AWVS Engine error invalid checksum

### ISSUE THREAD

**Issue by vinavon** [0xgkd/awvs#14]
Main installation is on server A
AWVS engine on server B

## Log Server B

```
root@9c46bf380314:/home/acunetix/.acunetix# cat logs/backend.log 

2024-10-27 15:32:46,098: ERROR helpers.licensing.license invalid checksum
2024-10-27 15:33:01,902: ERROR helpers.licensing.license invalid checksum
2024-10-27 15:33:03,732: ERROR helpers.licensing.license invalid checksum
2024-10-27 15:33:05,111: ERROR helpers.licensing.license invalid checksum
2024-10-27 15:33:06,464: ERROR helpers.licensing.license invalid checksum
2024-10-27 15:33:08,224: ERROR helpers.licensing.license invalid checksum
root@9c46bf380314:/home/acunetix/.acunetix# 
```
```
2024-10-27 15:39:15,432: WARNING api.handlers.scan InvalidAuth: no master set
2024-10-27 15:39:25,183: ERROR helpers.licensing.license invalid checksum
```

**Comment by vinavon** [comment]
Server A log


```
2024-10-27 14:28:09,975: INFO wsgi 172.17.0.1 - - [2024-10-27 14:28:09] "POST /graphql/ HTTP/1.1" 200 394 0.037145
2024-10-27 14:28:49,794: ERROR system_maintenance Scanning Engine response error None
2024-10-27 14:29:09,979: INFO wsgi 172.17.0.1 - - [2024-10-27 14:29:09] "POST /graphql/ HTTP/1.1" 200 394 0.038988
2024-10-27 14:30:09,982: INFO wsgi 172.17.0.1 - - [2024-10-27 14:30:09] "POST /graphql/ HTTP/1.1" 200 394 0.039851
2024-10-27 14:31:09,976: INFO wsgi 172.17.0.1 - - [2024-10-27 14:31:09] "POST /graphql/ HTTP/1.1" 200 394 0.040226
2024-10-27 14:32:09,972: INFO wsgi 172.17.0.1 - - [2024-10-27 14:32:09] "POST /graphql/ HTTP/1.1" 200 394 0.040355
2024-10-27 14:33:09,984: INFO wsgi 172.17.0.1 - - [2024-10-27 14:33:09] "POST /graphql/ HTTP/1.1" 200 394 0.042650
2024-10-27 14:33:51,526: ERROR system_maintenance Scanning Engine response error None
2024-10-27 14:34:09,982: INFO wsgi 172.17.0.1 - - [2024-10-27 14:34:09] "POST /graphql/ HTTP/1.1" 200 394 0.039031
2024-10-27 14:35:09,978: INFO wsgi 172.17.0.1 - - [2024-10-27 14:35:09] "POST /graphql/ HTTP/1.1" 200 394 0.039776
2024-10-27 14:36:09,969: INFO wsgi 172.17.0.1 - - [2024-10-27 14:36:09] "POST /graphql/ HTTP/1.1" 200 394 0.030198
2024-10-27 14:37:09,969: INFO wsgi 172.17.0.1 - - [2024-10-27 14:37:09] "POST /graphql/ HTTP/1.1" 200 394 0.030055
2024-10-27 14:38:09,998: INFO wsgi 172.17.0.1 - - [2024-10-27 14:38:09] "POST /graphql/ HTTP/1.1" 200 394 0.048872
2024-10-27 14:38:53,798: ERROR system_maintenance Scanning Engine response error None
2024-10-27 14:39:09,986: INFO wsgi 172.17.0.1 - - [2024-10-27 14:39:09] "POST /graphql/ HTTP/1.1" 200 394 0.040940
2024-10-27 14:40:09,980: INFO wsgi 172.17.0.1 - - [2024-10-27 14:40:09] "POST /graphql/ HTTP/1.1" 200 394 0.034973
2024-10-27 14:41:09,981: INFO wsgi 172.17.0.1 - - [2024-10-27 14:41:09] "POST /graphql/ HTTP/1.1" 200 394 0.040978
2024-10-27 14:42:09,992: INFO wsgi 172.17.0.1 - - [2024-10-27 14:42:09] "POST /graphql/ HTTP/1.1" 200 394 0.039774
2024-10-27 14:43:09,987: INFO wsgi 172.17.0.1 - - [2024-10-27 14:43:09] "POST /graphql/ HTTP/1.1" 200 394 0.038899
2024-10-27 14:43:55,603: ERROR system_maintenance Scanning Engine response error None
2024-10-27 14:44:09,992: INFO wsgi 172.17.0.1 - - [2024-10-27 14:44:09] "POST /graphql/ HTTP/1.1" 200 394 0.045079
2024-10-27 14:45:09,989: INFO wsgi 172.17.0.1 - - [2024-10-27 14:45:09] "POST /graphql/ HTTP/1.1" 200 394 0.040070
2024-10-27 14:46:09,994: INFO wsgi 172.17.0.1 - - [2024-10-27 14:46:09] "POST /graphql/ HTTP/1.1" 200 394 0.040877
2024-10-27 14:47:09,981: INFO wsgi 172.17.0.1 - - [2024-10-27 14:47:09] "POST /graphql/ HTTP/1.1" 200 394 0.038169
2024-10-27 14:48:09,996: INFO wsgi 172.17.0.1 - - [2024-10-27 14:48:09] "POST /graphql/ HTTP/1.1" 200 394 0.044236
2024-10-27 14:48:57,157: ERROR system_maintenance Scanning Engine response error None
2024-10-27 14:49:10,017: INFO wsgi 172.17.0.1 - - [2024-10-27 14:49:10] "POST /graphql/ HTTP/1.1" 200 394 0.056669
2024-10-27 14:50:09,957: INFO wsgi 172.17.0.1 - - [2024-10-27 14:50:09] "POST /graphql/ HTTP/1.1" 200 394 0.015521
2024-10-27 14:51:10,011: INFO wsgi 172.17.0.1 - - [2024-10-27 14:51:10] "POST /graphql/ HTTP/1.1" 200 394 0.048144
2024-10-27 14:52:09,993: INFO wsgi 172.17.0.1 - - [2024-10-27 14:52:09] "POST /graphql/ HTTP/1.1" 200 394 0.040576
2024-10-27 14:53:09,987: INFO wsgi 172.17.0.1 - - [2024-10-27 14:53:09] "POST /graphql/ HTTP/1.1" 200 394 0.037539
2024-10-27 14:53:58,780: ERROR system_maintenance Scanning Engine response error None
2024-10-27 14:54:09,999: INFO wsgi 172.17.0.1 - - [2024-10-27 14:54:09] "POST /graphql/ HTTP/1.1" 200 394 0.041056
2024-10-27 14:55:10,033: INFO wsgi 172.17.0.1 - - [2024-10-27 14:55:10] "POST /graphql/ HTTP/1.1" 200 394 0.041031
2024-10-27 14:56:11,541: INFO wsgi 172.17.0.1 - - [2024-10-27 14:56:11] "POST /graphql/ HTTP/1.1" 200 394 0.029726
2024-10-27 14:57:10,012: INFO wsgi 172.17.0.1 - - [2024-10-27 14:57:10] "POST /graphql/ HTTP/1.1" 200 394 0.040786
2024-10-27 14:58:10,479: INFO wsgi 172.17.0.1 - - [2024-10-27 14:58:10] "POST /graphql/ HTTP/1.1" 200 394 0.528899
2024-10-27 14:59:01,165: ERROR system_maintenance Scanning Engine response error None
2024-10-27 14:59:09,990: INFO wsgi 172.17.0.1 - - [2024-10-27 14:59:09] "POST /graphql/ HTTP/1.1" 200 394 0.041614
2024-10-27 15:00:09,998: INFO wsgi 172.17.0.1 - - [2024-10-27 15:00:09] "POST /graphql/ HTTP/1.1" 200 394 0.040775
2024-10-27 15:01:09,977: INFO wsgi 172.17.0.1 - - [2024-10-27 15:01:09] "POST /graphql/ HTTP/1.1" 200 394 0.019281
2024-10-27 15:02:10,027: INFO wsgi 172.17.0.1 - - [2024-10-27 15:02:10] "POST /graphql/ HTTP/1.1" 200 394 0.038391
2024-10-27 15:02:30,080: INFO wsgi 172.17.0.1 - - [2024-10-27 15:02:30] "POST /graphql/ HTTP/1.1" 200 394 0.038358
2024-10-27 15:02:33,984: INFO wsgi 172.17.0.1 - - [2024-10-27 15:02:33] "POST /graphql/ HTTP/1.1" 200 394 0.032876
2024-10-27 15:02:38,990: INFO wsgi 172.17.0.1 - - [2024-10-27 15:02:38] "POST /graphql/ HTTP/1.1" 200 394 0.041313
2024-10-27 15:02:43,995: INFO wsgi 172.17.0.1 - - [2024-10-27 15:02:43] "POST /graphql/ HTTP/1.1" 200 394 0.040024
2024-10-27 15:02:48,998: INFO wsgi 172.17.0.1 - - [2024-10-27 15:02:48] "POST /graphql/ HTTP/1.1" 200 394 0.045030
2024-10-27 15:02:53,974: INFO wsgi 172.17.0.1 - - [2024-10-27 15:02:53] "POST /graphql/ HTTP/1.1" 200 394 0.015365
2024-10-27 15:02:58,996: INFO wsgi 172.17.0.1 - - [2024-10-27 15:02:58] "POST /graphql/ HTTP/1.1" 200 394 0.049116
2024-10-27 15:03:03,972: INFO wsgi 172.17.0.1 - - [2024-10-27 15:03:03] "POST /graphql/ HTTP/1.1" 200 394 0.011086
2024-10-27 15:03:08,978: INFO wsgi 172.17.0.1 - - [2024-10-27 15:03:08] "POST /graphql/ HTTP/1.1" 200 394 0.025370
2024-10-27 15:03:13,999: INFO wsgi 172.17.0.1 - - [2024-10-27 15:03:13] "POST /graphql/ HTTP/1.1" 200 394 0.040968
2024-10-27 15:03:18,986: INFO wsgi 172.17.0.1 - - [2024-10-27 15:03:18] "POST /graphql/ HTTP/1.1" 200 394 0.028621
2024-10-27 15:03:24,000: INFO wsgi 172.17.0.1 - - [2024-10-27 15:03:23] "POST /graphql/ HTTP/1.1" 200 394 0.038814
2024-10-27 15:03:29,007: INFO wsgi 172.17.0.1 - - [2024-10-27 15:03:29] "POST /graphql/ HTTP/1.1" 200 394 0.048010
2024-10-27 15:03:32,941: INFO wsgi 172.17.0.1 - - [2024-10-27 15:03:32] "GET / HTTP/1.1" 200 11584 0.001734
2024-10-27 15:03:33,999: INFO wsgi 172.17.0.1 - - [2024-10-27 15:03:33] "POST /graphql/ HTTP/1.1" 200 394 0.038868
2024-10-27 15:03:38,998: INFO wsgi 172.17.0.1 - - [2024-10-27 15:03:38] "POST /graphql/ HTTP/1.1" 200 394 0.040996
2024-10-27 15:03:48,007: INFO wsgi 172.17.0.1 - - [2024-10-27 15:03:48] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.003080
2024-10-27 15:04:03,071: ERROR system_maintenance Scanning Engine response error None
2024-10-27 15:04:09,507: INFO wsgi 172.17.0.1 - - [2024-10-27 15:04:09] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.003949
2024-10-27 15:04:09,998: INFO wsgi 172.17.0.1 - - [2024-10-27 15:04:09] "POST /graphql/ HTTP/1.1" 200 394 0.039222
2024-10-27 15:05:10,000: INFO wsgi 172.17.0.1 - - [2024-10-27 15:05:09] "POST /graphql/ HTTP/1.1" 200 394 0.038876
2024-10-27 15:05:36,445: INFO wsgi 172.17.0.1 - - [2024-10-27 15:05:36] "GET / HTTP/1.1" 200 11584 0.001471
2024-10-27 15:06:10,012: INFO wsgi 172.17.0.1 - - [2024-10-27 15:06:10] "POST /graphql/ HTTP/1.1" 200 394 0.041563
2024-10-27 15:07:09,997: INFO wsgi 172.17.0.1 - - [2024-10-27 15:07:09] "POST /graphql/ HTTP/1.1" 200 394 0.039027
2024-10-27 15:08:10,722: INFO wsgi 172.17.0.1 - - [2024-10-27 15:08:10] "POST /graphql/ HTTP/1.1" 200 394 0.764249
2024-10-27 15:08:32,064: INFO wsgi 172.17.0.1 - - [2024-10-27 15:08:32] "GET / HTTP/1.1" 200 11584 0.001762
2024-10-27 15:08:40,223: INFO wsgi 172.17.0.1 - - [2024-10-27 15:08:40] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.003239
2024-10-27 15:09:05,407: ERROR system_maintenance Scanning Engine response error None
2024-10-27 15:09:10,001: INFO wsgi 172.17.0.1 - - [2024-10-27 15:09:10] "POST /graphql/ HTTP/1.1" 200 394 0.042238
2024-10-27 15:10:10,001: INFO wsgi 172.17.0.1 - - [2024-10-27 15:10:10] "POST /graphql/ HTTP/1.1" 200 394 0.037424
2024-10-27 15:11:10,022: INFO wsgi 172.17.0.1 - - [2024-10-27 15:11:10] "POST /graphql/ HTTP/1.1" 200 394 0.046699
2024-10-27 15:12:10,011: INFO wsgi 172.17.0.1 - - [2024-10-27 15:12:10] "POST /graphql/ HTTP/1.1" 200 394 0.040837
2024-10-27 15:13:09,974: INFO wsgi 172.17.0.1 - - [2024-10-27 15:13:09] "POST /graphql/ HTTP/1.1" 200 394 0.014237
2024-10-27 15:14:07,127: ERROR system_maintenance Scanning Engine response error None
2024-10-27 15:14:10,016: INFO wsgi 172.17.0.1 - - [2024-10-27 15:14:10] "POST /graphql/ HTTP/1.1" 200 394 0.041110
2024-10-27 15:15:09,999: INFO wsgi 172.17.0.1 - - [2024-10-27 15:15:09] "POST /graphql/ HTTP/1.1" 200 394 0.038744
2024-10-27 15:16:10,014: INFO wsgi 172.17.0.1 - - [2024-10-27 15:16:10] "POST /graphql/ HTTP/1.1" 200 394 0.037578
2024-10-27 15:17:10,012: INFO wsgi 172.17.0.1 - - [2024-10-27 15:17:10] "POST /graphql/ HTTP/1.1" 200 394 0.044844
2024-10-27 15:18:09,982: INFO wsgi 172.17.0.1 - - [2024-10-27 15:18:09] "POST /graphql/ HTTP/1.1" 200 394 0.015399
2024-10-27 15:18:11,328: INFO helpers.licensing re-activating
2024-10-27 15:19:09,634: ERROR system_maintenance Scanning Engine response error None
2024-10-27 15:19:10,004: INFO wsgi 172.17.0.1 - - [2024-10-27 15:19:10] "POST /graphql/ HTTP/1.1" 200 394 0.043296
2024-10-27 15:20:10,013: INFO wsgi 172.17.0.1 - - [2024-10-27 15:20:10] "POST /graphql/ HTTP/1.1" 200 394 0.040829
2024-10-27 15:21:09,979: INFO wsgi 172.17.0.1 - - [2024-10-27 15:21:09] "POST /graphql/ HTTP/1.1" 200 394 0.014312
2024-10-27 15:22:10,011: INFO wsgi 172.17.0.1 - - [2024-10-27 15:22:10] "POST /graphql/ HTTP/1.1" 200 394 0.039022
2024-10-27 15:23:10,014: INFO wsgi 172.17.0.1 - - [2024-10-27 15:23:10] "POST /graphql/ HTTP/1.1" 200 394 0.044688
2024-10-27 15:24:10,006: INFO wsgi 172.17.0.1 - - [2024-10-27 15:24:10] "POST /graphql/ HTTP/1.1" 200 394 0.039262
2024-10-27 15:24:11,556: ERROR system_maintenance Scanning Engine response error None
2024-10-27 15:25:10,006: INFO wsgi 172.17.0.1 - - [2024-10-27 15:25:10] "POST /graphql/ HTTP/1.1" 200 394 0.039210
2024-10-27 15:26:10,020: INFO wsgi 172.17.0.1 - - [2024-10-27 15:26:10] "POST /graphql/ HTTP/1.1" 200 394 0.050364
2024-10-27 15:27:10,002: INFO wsgi 172.17.0.1 - - [2024-10-27 15:27:10] "POST /graphql/ HTTP/1.1" 200 394 0.038120
2024-10-27 15:28:10,016: INFO wsgi 172.17.0.1 - - [2024-10-27 15:28:10] "POST /graphql/ HTTP/1.1" 200 394 0.041662
2024-10-27 15:28:58,741: INFO wsgi 172.17.0.1 - - [2024-10-27 15:28:58] "POST /worker/v1/status/v1/workers/ HTTP/1.1" 404 280 0.001352
2024-10-27 15:29:07,593: INFO wsgi 172.17.0.1 - - [2024-10-27 15:29:07] "POST /worker/status/v1/workers/ HTTP/1.1" 404 280 0.000995
2024-10-27 15:29:10,019: INFO wsgi 172.17.0.1 - - [2024-10-27 15:29:10] "POST /graphql/ HTTP/1.1" 200 394 0.047248
2024-10-27 15:29:11,933: INFO wsgi 172.17.0.1 - - [2024-10-27 15:29:11] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.001623
2024-10-27 15:29:12,774: ERROR system_maintenance Scanning Engine response error None
2024-10-27 15:29:58,120: INFO wsgi 172.17.0.1 - - [2024-10-27 15:29:58] "POST /worker/v1/status/v1/workers/ HTTP/1.1" 404 280 0.001283
2024-10-27 15:30:03,383: INFO wsgi 172.17.0.1 - - [2024-10-27 15:30:03] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.002410
2024-10-27 15:30:08,722: INFO wsgi 172.17.0.1 - - [2024-10-27 15:30:08] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.002333
2024-10-27 15:30:10,019: INFO wsgi 172.17.0.1 - - [2024-10-27 15:30:10] "POST /graphql/ HTTP/1.1" 200 394 0.040586
2024-10-27 15:30:10,398: INFO wsgi 172.17.0.1 - - [2024-10-27 15:30:10] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.002249
2024-10-27 15:30:14,144: INFO wsgi 172.17.0.1 - - [2024-10-27 15:30:14] "POST /a/status/v1/workers/ HTTP/1.1" 404 280 0.001136
2024-10-27 15:30:35,996: INFO wsgi 172.17.0.1 - - [2024-10-27 15:30:35] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.002407
2024-10-27 15:31:09,983: INFO wsgi 172.17.0.1 - - [2024-10-27 15:31:09] "POST /graphql/ HTTP/1.1" 200 394 0.011528
2024-10-27 15:32:09,999: INFO wsgi 172.17.0.1 - - [2024-10-27 15:32:09] "POST /graphql/ HTTP/1.1" 200 394 0.024763
2024-10-27 15:32:46,596: INFO wsgi 172.17.0.1 - - [2024-10-27 15:32:46] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.002439
2024-10-27 15:33:02,542: INFO wsgi 172.17.0.1 - - [2024-10-27 15:33:02] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.002712
2024-10-27 15:33:04,234: INFO wsgi 172.17.0.1 - - [2024-10-27 15:33:04] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.001918
2024-10-27 15:33:05,599: INFO wsgi 172.17.0.1 - - [2024-10-27 15:33:05] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.001043
2024-10-27 15:33:06,953: INFO wsgi 172.17.0.1 - - [2024-10-27 15:33:06] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.003485
2024-10-27 15:33:08,688: INFO wsgi 172.17.0.1 - - [2024-10-27 15:33:08] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.003380
2024-10-27 15:33:09,989: INFO wsgi 172.17.0.1 - - [2024-10-27 15:33:09] "POST /graphql/ HTTP/1.1" 200 394 0.015300
2024-10-27 15:34:09,997: INFO wsgi 172.17.0.1 - - [2024-10-27 15:34:09] "POST /graphql/ HTTP/1.1" 200 394 0.014954
2024-10-27 15:34:14,093: ERROR system_maintenance Scanning Engine response error None
2024-10-27 15:35:10,007: INFO wsgi 172.17.0.1 - - [2024-10-27 15:35:10] "POST /graphql/ HTTP/1.1" 200 394 0.023557
2024-10-27 15:36:10,014: INFO wsgi 172.17.0.1 - - [2024-10-27 15:36:10] "POST /graphql/ HTTP/1.1" 200 394 0.032017
2024-10-27 15:36:48,115: INFO wsgi 172.17.0.1 - - [2024-10-27 15:36:48] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.002539
2024-10-27 15:37:10,015: INFO wsgi 172.17.0.1 - - [2024-10-27 15:37:10] "POST /graphql/ HTTP/1.1" 200 394 0.024637
2024-10-27 15:38:10,006: INFO wsgi 172.17.0.1 - - [2024-10-27 15:38:10] "POST /graphql/ HTTP/1.1" 200 394 0.029054
2024-10-27 15:38:58,585: INFO wsgi 172.17.0.1 - - [2024-10-27 15:38:58] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.003905
2024-10-27 15:39:10,027: INFO wsgi 172.17.0.1 - - [2024-10-27 15:39:10] "POST /graphql/ HTTP/1.1" 200 394 0.033030
2024-10-27 15:39:15,497: ERROR system_maintenance Scanning Engine response error None
2024-10-27 15:39:26,704: INFO wsgi 172.17.0.1 - - [2024-10-27 15:39:26] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.002474
2024-10-27 15:40:10,024: INFO wsgi 172.17.0.1 - - [2024-10-27 15:40:10] "POST /graphql/ HTTP/1.1" 200 394 0.036294
2024-10-27 15:41:10,015: INFO wsgi 172.17.0.1 - - [2024-10-27 15:41:10] "POST /graphql/ HTTP/1.1" 200 394 0.024681
```

**Comment by vinavon** [comment]
more log

main installation
```

2024-10-27 16:59:41,459: DEBUG server.application handling get:https:/api/v1/me

2024-10-27 16:59:41,461: DEBUG server.application handling get:https:/api/v1/info/config_flags

2024-10-27 16:59:41,465: DEBUG server.application handling get:https:/api/v1/info

2024-10-27 16:59:41,492: INFO wsgi 172.17.0.1 - - [2024-10-27 16:59:41] "GET /api/v1/info/config_flags HTTP/1.1" 200 2430 0.030440

2024-10-27 16:59:41,498: INFO wsgi 172.17.0.1 - - [2024-10-27 16:59:41] "GET /api/v1/me HTTP/1.1" 200 883 0.038855

2024-10-27 16:59:41,503: INFO wsgi 172.17.0.1 - - [2024-10-27 16:59:41] "GET /api/v1/info HTTP/1.1" 200 2093 0.038208

2024-10-27 16:59:41,591: DEBUG server.application handling get:https:/api/v1/workers

2024-10-27 16:59:41,629: INFO wsgi 172.17.0.1 - - [2024-10-27 16:59:41] "GET /api/v1/workers HTTP/1.1" 200 643 0.037978

2024-10-27 16:59:41,660: INFO wsgi 172.17.0.1 - - [2024-10-27 16:59:41] "POST /graphql/ HTTP/1.1" 200 6506 0.107401

2024-10-27 16:59:41,661: INFO wsgi 172.17.0.1 - - [2024-10-27 16:59:41] "POST /graphql/ HTTP/1.1" 200 6506 0.068120

2024-10-27 16:59:44,833: DEBUG server.application handling post:https:/status/v1/workers/

2024-10-27 16:59:44,837: INFO wsgi 172.17.0.1 - - [2024-10-27 16:59:44] "POST /status/v1/workers/ HTTP/1.1" 409 293 0.003273
```

engine
```
172.17.0.1 - - [2024-10-27 16:58:57] "POST /api/v1/register HTTP/1.1" 409 338 0.632425

2024-10-27 16:59:44,306: DEBUG server.application handling post:https:/api/v1/register

2024-10-27 16:59:44,307: DEBUG helpers.licensing get_local_license: installation_id is not set

2024-10-27 16:59:44,307: ERROR helpers.licensing.license invalid checksum

2024-10-27 16:59:44,308: DEBUG root connecting to https://100.106.253.57:3443/status/v1

2024-10-27 16:59:44,309: DEBUG urllib3.connectionpool Starting new HTTPS connection (1): 100.106.253.57:3443

2024-10-27 16:59:45,076: DEBUG urllib3.connectionpool https://100.106.253.57:3443 "POST /status/v1/workers/ HTTP/11" 409 None

172.17.0.1 - - [2024-10-27 16:59:45] "POST /api/v1/register HTTP/1.1" 409 338 0.772748

2024-10-27 17:00:26,936: DEBUG server.application handling post:https:/api/v1/register

2024-10-27 17:00:26,936: DEBUG helpers.licensing get_local_license: installation_id is not set

2024-10-27 17:00:26,937: ERROR helpers.licensing.license invalid checksum

2024-10-27 17:00:26,937: DEBUG root connecting to https://100.106.253.57:3443/status/v1

2024-10-27 17:00:26,939: DEBUG urllib3.connectionpool Starting new HTTPS connection (1): 100.106.253.57:3443

2024-10-27 17:00:27,564: DEBUG urllib3.connectionpool https://100.106.253.57:3443 "POST /status/v1/workers/ HTTP/11" 409 None

172.17.0.1 - - [2024-10-27 17:00:27] "POST /api/v1/register HTTP/1.1" 409 338 0.630232
```

**Comment by 0xgkd** [comment]
@vinavon Updated, please refer to the README. Multi-engine authentication must use container internal address.

**Comment by vinavon** [comment]
What a benefit for using multi engine in same computer / container ?
I have two docker, screenshot from portainer docker.

![{17E7442A-8395-4CFD-96FB-1AA92B46AAC5}](https://github.com/user-attachments/assets/2d5af805-7b62-44d2-aade-3ff655c77db4)

**Comment by 0xgkd** [comment]
@vinavon Enable multiple engines/containers on the same computer can improve the resource utilization of a single machine (usually memory).

Sorry, I am not familiar with the portainer docker network environment. If you want to enable multiple engines on portainer docker, you must ensure that communication addresses between the two containers, main installation and engine, can access each other, so that the engine can be registered successfully.

Hope you enjoy using acunetix and multi-engine.

**Comment by vinavon** [comment]
>  I am not familiar with the portainer docker network environment

portainer docker is web ui for manage docker.

> communication addresses between the two containers

communication is ok, docker is in local network, i just guess about this error

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "gevent/baseserver.py", line 34, in _handle_and_close_when_done
  File "gevent/server.py", line 209, in wrap_socket_and_handle
  File "gevent/ssl.py", line 120, in wrap_socket
  File "gevent/ssl.py", line 349, in __init__
  File "gevent/ssl.py", line 724, in do_handshake
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] ssl/tls alert certificate unknown (_ssl.c:1000)
```
