### ISSUE TITLE
centos9不能运行

### ISSUE THREAD

**Issue by yardian** [0xgkd/awvs#6]
2024-08-01 02:30:55,025: ERROR helpers.tm telemetry communication failed with HTTPSConnectionPool(host='telemetry.invicti.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff19c3cb30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
attempting to stop previous message brokers
attempting to stop previous database
pg_ctl: could not send stop signal (PID: 37): No such process
attempting to start the db
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....2024-08-01 02:31:41.182 UTC [37] LOG:  starting PostgreSQL 13.14 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit
2024-08-01 02:31:41.183 UTC [37] LOG:  listening on IPv6 address "::1", port 35432
2024-08-01 02:31:41.183 UTC [37] LOG:  listening on IPv4 address "127.0.0.1", port 35432
2024-08-01 02:31:41.195 UTC [37] LOG:  listening on Unix socket "/tmp/.s.PGSQL.35432"
2024-08-01 02:31:41.199 UTC [38] LOG:  database system was interrupted; last known up at 2024-08-01 02:30:33 UTC
2024-08-01 02:31:41.496 UTC [38] LOG:  database system was not properly shut down; automatic recovery in progress
2024-08-01 02:31:41.498 UTC [38] LOG:  redo starts at 0/18300D8
2024-08-01 02:31:41.499 UTC [38] LOG:  invalid record length at 0/18301C0: wanted 24, got 0
2024-08-01 02:31:41.499 UTC [38] LOG:  redo done at 0/1830188
2024-08-01 02:31:41.503 UTC [37] LOG:  database system is ready to accept connections
 done
server started
chmod: cannot access '/home/acunetix/.acunetix/v_240626115/broker/server.conf': No such file or directory
sed: can't read /home/acunetix/.acunetix/v_240626115/broker/server.conf: No such file or directory
sed: can't read /home/acunetix/.acunetix/v_240626115/broker/server.conf: No such file or directory
sed: can't read /home/acunetix/.acunetix/v_240626115/broker/server.conf: No such file or directory
sed: can't read /home/acunetix/.acunetix/v_240626115/broker/server.conf: No such file or directory
sed: can't read /home/acunetix/.acunetix/v_240626115/broker/server.conf: No such file or directory
attempting to start the message broker
nats-server: open /home/acunetix/.acunetix/v_240626115/broker/server.conf: no such file or directory
attempting to stop previous integrations services
attempting to start the backend
2024-08-01 02:31:45,033: WARNING application.init unhandled config key wvs.temp_dir, ignoring
2024-08-01 02:31:45,033: WARNING application.init invalid config entry , ignoring
2024-08-01 02:31:45,033: WARNING application.init unhandled config key aes_encryption_key, ignoring
2024-08-01 02:31:45,034: WARNING application.init invalid config entry , ignoring
2024-08-01 02:31:45,034: INFO helpers.application.util base_app_storage is set, using it
2024-08-01 02:31:45,034: INFO helpers.application.util base_user_storage is set, using it
2024-08-01 02:31:45,034: INFO helpers.application.util Storage root: /home/acunetix/.acunetix
2024-08-01 02:31:45,037: INFO application.init Checking database connection...
2024-08-01 02:31:45,050: INFO application.init Database connection OK. Found database version: 240500
2024-08-01 02:31:45,053: INFO application.init Database version: 240500
2024-08-01 02:31:45,053: INFO application.init Running database update script: update_database.sql
2024-08-01 02:31:45,078: INFO application.init Database version: 240500
2024-08-01 02:31:45,078: INFO application.init Running database update script: static_data.sql
2024-08-01 02:31:45,120: INFO application.init Database maintenance done
2024-08-01 02:31:45,122: ERROR root chown failed with [Errno 1] Operation not permitted: '/home/acunetix/.acunetix/data/license/license_info.json'
Traceback (most recent call last):
  File "helpers/application/access_rights.py", line 12, in chmod
PermissionError: [Errno 1] Operation not permitted: '/home/acunetix/.acunetix/data/license/license_info.json'
2024-08-01 02:31:46,234: INFO service.master creating system proxy callback
2024-08-01 02:31:46,238: INFO helpers.application.util Starting app, version: 24.6.240626115 [Linux] (gev:24.2.1)
2024-08-01 02:31:46,241: INFO service.master Database version: 240500
2024-08-01 02:31:46,241: INFO service.master starting backend
2024-08-01 02:31:46,242: INFO service.master getting license
2024-08-01 02:31:47,001: INFO helpers.application.util adjusting ca bundle...
2024-08-01 02:31:47,001: INFO helpers.application.util settings ca value: None
2024-08-01 02:31:47,025: INFO helpers.security_blob.loader attempting to download the latest blob
2024-08-01 02:31:47,883: INFO helpers.security_blob.loader Loaded the security blob: /home/acunetix/.acunetix/data/security/security_240626088.bin
2024-08-01 02:31:48,005: INFO helpers.security_blob.loader BlobLoader initialized
2024-08-01 02:31:48,005: INFO service.master creating system updater
2024-08-01 02:31:48.016 UTC [64] ERROR:  duplicate key value violates unique constraint "schedules_owner_id_unique_id_uindex"
2024-08-01 02:31:48.016 UTC [64] DETAIL:  Key (owner_id, unique_id)=(986ad8c0-a5b3-df4d-7028-d5f3c06e936c, process_all_fqdn_if_scheduled) already exists.
2024-08-01 02:31:48.016 UTC [64] STATEMENT:  INSERT INTO schedules (schedule_id, owner_id, created, next_run, unique_id, trigger_interval, rate_count, rate_delta, task) VALUES ('d8131691-b613-4c1a-a825-41c5b0495f4a'::UUID, '986ad8c0a5b3df4d7028d5f3c06e936c'::UUID, '2024-08-01T02:31:48.013665+00:00'::timestamptz, '2024-08-01T02:31:48.013665+00:00'::timestamptz, 'process_all_fqdn_if_scheduled', '1 days 0.000000 seconds'::interval, 4, 3600, '{"handler": "process_all_fqdn_if_scheduled", "data": {"owner_id": "986ad8c0a5b3df4d7028d5f3c06e936c", "shard": "master"}}')
2024-08-01 02:31:48,022: INFO service.master registering session handlers
2024-08-01 02:31:48,023: INFO service.master status api on https://localhost:3443/status/v1/
2024-08-01 02:31:48,024: INFO service.master Initialization of messaging broker and streams...
2024-08-01 02:31:48,024: WARNING service.master Unexpected error happened during messaging streams initialization (e.g. server is not running): Couldn't find the nats-server.conf file at /home/acunetix/.acunetix/v_240626115/scanner/../broker/nats-server.conf
2024-08-01 02:31:48,024: WARNING service.master Messaging client initialization will be skipped and events will not be published.
2024-08-01 02:31:48,025: WARNING service.master Subscription in message broker was not successfully done: 'NoneType' object has no attribute 'subscribe_for_message'
2024-08-01 02:31:48,025: INFO service.master creating the broker
2024-08-01 02:31:48,025: INFO service.master starting the broker
2024-08-01 02:31:48,026: INFO service.master starting the db_based_scheduler
2024-08-01 02:31:48,037: INFO service.master creating the http server
2024-08-01 02:31:48,060: INFO server.routers.api.routes checking _routes:
2024-08-01 02:31:48,065: INFO server.routers.api.routes checking _routes:
2024-08-01 02:31:48,073: INFO server.routers.api.routes checking _routes:
2024-08-01 02:31:48,074: INFO server.static.router creating route for /home/acunetix/.acunetix/v_240626115/vue-ui (base path /app)
2024-08-01 02:31:48,107: INFO server.static.router indexed 507 files
2024-08-01 02:31:48,107: INFO server.static.router skipped 0 files
2024-08-01 02:31:48,107: INFO server.static.router creating route for /home/acunetix/.acunetix/v_240626115/ui (base path None)
2024-08-01 02:31:48,125: INFO server.static.router indexed 130 files
2024-08-01 02:31:48,125: INFO server.static.router skipped 0 files
2024-08-01 02:31:48,125: INFO server.application server application initialized
2024-08-01 02:31:48,390: INFO service.master starting the http server
2024-08-01 02:31:48,396: INFO service.master starting the reporter
2024-08-01 02:31:48,396: INFO service.master reporter worker started
2024-08-01 02:31:48,397: INFO reporter wvs_basedir /home/acunetix/.acunetix/v_240626115/scanner
2024-08-01 02:31:48,397: INFO reporter searching for pdf generator...
2024-08-01 02:31:48,397: INFO reporter trying /home/acunetix/.acunetix/v_240626115/scanner/pdf
2024-08-01 02:31:48,397: INFO reporter trying /home/acunetix/.acunetix/v_240626115/scanner/pdf.exe
2024-08-01 02:31:48,398: INFO reporter trying /home/acunetix/.acunetix/v_240626115/scanner/node
2024-08-01 02:31:48,398: INFO reporter pdf_converter=['/home/acunetix/.acunetix/v_240626115/scanner/node', 'pdf']
2024-08-01 02:31:48,399: INFO service.master starting the system updater
2024-08-01 02:31:48,400: INFO helpers.updater update thread started
2024-08-01 02:31:48,400: INFO service.master starting the acumonitor thread
2024-08-01 02:31:48,402: INFO service.master starting the mailer thread
2024-08-01 02:31:48,402: INFO service.master starting lsr worker thread
2024-08-01 02:31:48,404: INFO service.master worker_checker started
2024-08-01 02:31:48,460: INFO xfqdn start fqdn processing for 986ad8c0a5b3df4d7028d5f3c06e936c
2024-08-01 02:31:48,475: WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c4011f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/DeleteTargets
2024-08-01 02:31:48,477: WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c400fe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/DeleteTargets
2024-08-01 02:31:48,477: WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c401e80>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/DeleteTargets
2024-08-01 02:31:48,478: ERROR xfqdn migration request failed with HTTPSConnectionPool(host='erp.acunetix.com', port=443): Max retries exceeded with url: /TargetManagement/Targets/DeleteTargets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c402030>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "urllib3/connection.py", line 196, in _new_conn
  File "urllib3/util/connection.py", line 85, in create_connection
  File "urllib3/util/connection.py", line 73, in create_connection
  File "gevent/_socketcommon.py", line 590, in connect
  File "gevent/_socketcommon.py", line 634, in _internal_connect
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 615, in connect
  File "urllib3/connection.py", line 211, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fe02c402030>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "helpers/licensing/targets/fqdn.py", line 1073, in process_all_fqdn_by_owner_and_type
  File "helpers/licensing/targets/service.py", line 214, in uninstall
  File "helpers/licensing/targets/service.py", line 195, in do_request
  File "urllib3/_request_methods.py", line 144, in request
  File "urllib3/_request_methods.py", line 279, in request_encode_body
  File "urllib3/poolmanager.py", line 443, in urlopen
  File "urllib3/connectionpool.py", line 873, in urlopen
  File "urllib3/connectionpool.py", line 873, in urlopen
  File "urllib3/connectionpool.py", line 873, in urlopen
  File "urllib3/connectionpool.py", line 843, in urlopen
  File "urllib3/util/retry.py", line 519, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='erp.acunetix.com', port=443): Max retries exceeded with url: /TargetManagement/Targets/DeleteTargets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c402030>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-08-01 02:31:48,487: WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c403830>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/GetTargets
2024-08-01 02:31:48,489: WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c4183b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/GetTargets
2024-08-01 02:31:48,491: WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c418b60>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/GetTargets
2024-08-01 02:31:48,492: ERROR xfqdn error reaching target management service HTTPSConnectionPool(host='erp.acunetix.com', port=443): Max retries exceeded with url: /TargetManagement/Targets/GetTargets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c419250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "urllib3/connection.py", line 196, in _new_conn
  File "urllib3/util/connection.py", line 85, in create_connection
  File "urllib3/util/connection.py", line 73, in create_connection
  File "gevent/_socketcommon.py", line 590, in connect
  File "gevent/_socketcommon.py", line 634, in _internal_connect
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 615, in connect
  File "urllib3/connection.py", line 211, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fe02c419250>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "helpers/licensing/targets/fqdn.py", line 1101, in process_all_fqdn_by_owner_and_type
  File "helpers/licensing/targets/service.py", line 259, in get_targets
  File "helpers/licensing/targets/service.py", line 195, in do_request
  File "urllib3/_request_methods.py", line 144, in request
  File "urllib3/_request_methods.py", line 279, in request_encode_body
  File "urllib3/poolmanager.py", line 443, in urlopen
  File "urllib3/connectionpool.py", line 873, in urlopen
  File "urllib3/connectionpool.py", line 873, in urlopen
  File "urllib3/connectionpool.py", line 873, in urlopen
  File "urllib3/connectionpool.py", line 843, in urlopen
  File "urllib3/util/retry.py", line 519, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='erp.acunetix.com', port=443): Max retries exceeded with url: /TargetManagement/Targets/GetTargets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c419250>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-08-01 02:31:48,494: INFO xfqdn end fqdn processing for 986ad8c0a5b3df4d7028d5f3c06e936c
2024-08-01 02:31:48,500: INFO helpers.licensing re-activating
2024-08-01 02:31:49,015: INFO application.init Vtypes updated in 1.0014197549999153 seconds
2024-08-01 02:31:49,405: INFO service.master system init completed.
2024-08-01 02:31:49,407: INFO service.master Platform: Linux,Ubuntu 18.04.6 LTS,5.14.0-427.13.1.el9_4.x86_64,2.27

**Comment by 0xgkd** [comment]
> 2024-08-01 02:30:55,025: ERROR helpers.tm telemetry communication failed with HTTPSConnectionPool(host='telemetry.invicti.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff19c3cb30>: Failed to establish a new connection: [Errno 101] Network is unreachable')) attempting to stop previous message brokers attempting to stop previous database pg_ctl: could not send stop signal (PID: 37): No such process attempting to start the db pg_ctl: another server might be running; trying to start server anyway waiting for server to start....2024-08-01 02:31:41.182 UTC [37] LOG: starting PostgreSQL 13.14 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit 2024-08-01 02:31:41.183 UTC [37] LOG: listening on IPv6 address "::1", port 35432 2024-08-01 02:31:41.183 UTC [37] LOG: listening on IPv4 address "127.0.0.1", port 35432 2024-08-01 02:31:41.195 UTC [37] LOG: listening on Unix socket "/tmp/.s.PGSQL.35432" 2024-08-01 02:31:41.199 UTC [38] LOG: database system was interrupted; last known up at 2024-08-01 02:30:33 UTC 2024-08-01 02:31:41.496 UTC [38] LOG: database system was not properly shut down; automatic recovery in progress 2024-08-01 02:31:41.498 UTC [38] LOG: redo starts at 0/18300D8 2024-08-01 02:31:41.499 UTC [38] LOG: invalid record length at 0/18301C0: wanted 24, got 0 2024-08-01 02:31:41.499 UTC [38] LOG: redo done at 0/1830188 2024-08-01 02:31:41.503 UTC [37] LOG: database system is ready to accept connections done server started chmod: cannot access '/home/acunetix/.acunetix/v_240626115/broker/server.conf': No such file or directory sed: can't read /home/acunetix/.acunetix/v_240626115/broker/server.conf: No such file or directory sed: can't read /home/acunetix/.acunetix/v_240626115/broker/server.conf: No such file or directory sed: can't read /home/acunetix/.acunetix/v_240626115/broker/server.conf: No such file or directory sed: can't read /home/acunetix/.acunetix/v_240626115/broker/server.conf: No such file or directory sed: can't read /home/acunetix/.acunetix/v_240626115/broker/server.conf: No such file or directory attempting to start the message broker nats-server: open /home/acunetix/.acunetix/v_240626115/broker/server.conf: no such file or directory attempting to stop previous integrations services attempting to start the backend 2024-08-01 02:31:45,033: WARNING application.init unhandled config key wvs.temp_dir, ignoring 2024-08-01 02:31:45,033: WARNING application.init invalid config entry , ignoring 2024-08-01 02:31:45,033: WARNING application.init unhandled config key aes_encryption_key, ignoring 2024-08-01 02:31:45,034: WARNING application.init invalid config entry , ignoring 2024-08-01 02:31:45,034: INFO helpers.application.util base_app_storage is set, using it 2024-08-01 02:31:45,034: INFO helpers.application.util base_user_storage is set, using it 2024-08-01 02:31:45,034: INFO helpers.application.util Storage root: /home/acunetix/.acunetix 2024-08-01 02:31:45,037: INFO application.init Checking database connection... 2024-08-01 02:31:45,050: INFO application.init Database connection OK. Found database version: 240500 2024-08-01 02:31:45,053: INFO application.init Database version: 240500 2024-08-01 02:31:45,053: INFO application.init Running database update script: update_database.sql 2024-08-01 02:31:45,078: INFO application.init Database version: 240500 2024-08-01 02:31:45,078: INFO application.init Running database update script: static_data.sql 2024-08-01 02:31:45,120: INFO application.init Database maintenance done 2024-08-01 02:31:45,122: ERROR root chown failed with [Errno 1] Operation not permitted: '/home/acunetix/.acunetix/data/license/license_info.json' Traceback (most recent call last): File "helpers/application/access_rights.py", line 12, in chmod PermissionError: [Errno 1] Operation not permitted: '/home/acunetix/.acunetix/data/license/license_info.json' 2024-08-01 02:31:46,234: INFO service.master creating system proxy callback 2024-08-01 02:31:46,238: INFO helpers.application.util Starting app, version: 24.6.240626115 [Linux] (gev:24.2.1) 2024-08-01 02:31:46,241: INFO service.master Database version: 240500 2024-08-01 02:31:46,241: INFO service.master starting backend 2024-08-01 02:31:46,242: INFO service.master getting license 2024-08-01 02:31:47,001: INFO helpers.application.util adjusting ca bundle... 2024-08-01 02:31:47,001: INFO helpers.application.util settings ca value: None 2024-08-01 02:31:47,025: INFO helpers.security_blob.loader attempting to download the latest blob 2024-08-01 02:31:47,883: INFO helpers.security_blob.loader Loaded the security blob: /home/acunetix/.acunetix/data/security/security_240626088.bin 2024-08-01 02:31:48,005: INFO helpers.security_blob.loader BlobLoader initialized 2024-08-01 02:31:48,005: INFO service.master creating system updater 2024-08-01 02:31:48.016 UTC [64] ERROR: duplicate key value violates unique constraint "schedules_owner_id_unique_id_uindex" 2024-08-01 02:31:48.016 UTC [64] DETAIL: Key (owner_id, unique_id)=(986ad8c0-a5b3-df4d-7028-d5f3c06e936c, process_all_fqdn_if_scheduled) already exists. 2024-08-01 02:31:48.016 UTC [64] STATEMENT: INSERT INTO schedules (schedule_id, owner_id, created, next_run, unique_id, trigger_interval, rate_count, rate_delta, task) VALUES ('d8131691-b613-4c1a-a825-41c5b0495f4a'::UUID, '986ad8c0a5b3df4d7028d5f3c06e936c'::UUID, '2024-08-01T02:31:48.013665+00:00'::timestamptz, '2024-08-01T02:31:48.013665+00:00'::timestamptz, 'process_all_fqdn_if_scheduled', '1 days 0.000000 seconds'::interval, 4, 3600, '{"handler": "process_all_fqdn_if_scheduled", "data": {"owner_id": "986ad8c0a5b3df4d7028d5f3c06e936c", "shard": "master"}}') 2024-08-01 02:31:48,022: INFO service.master registering session handlers 2024-08-01 02:31:48,023: INFO service.master status api on https://localhost:3443/status/v1/ 2024-08-01 02:31:48,024: INFO service.master Initialization of messaging broker and streams... 2024-08-01 02:31:48,024: WARNING service.master Unexpected error happened during messaging streams initialization (e.g. server is not running): Couldn't find the nats-server.conf file at /home/acunetix/.acunetix/v_240626115/scanner/../broker/nats-server.conf 2024-08-01 02:31:48,024: WARNING service.master Messaging client initialization will be skipped and events will not be published. 2024-08-01 02:31:48,025: WARNING service.master Subscription in message broker was not successfully done: 'NoneType' object has no attribute 'subscribe_for_message' 2024-08-01 02:31:48,025: INFO service.master creating the broker 2024-08-01 02:31:48,025: INFO service.master starting the broker 2024-08-01 02:31:48,026: INFO service.master starting the db_based_scheduler 2024-08-01 02:31:48,037: INFO service.master creating the http server 2024-08-01 02:31:48,060: INFO server.routers.api.routes checking _routes: 2024-08-01 02:31:48,065: INFO server.routers.api.routes checking _routes: 2024-08-01 02:31:48,073: INFO server.routers.api.routes checking _routes: 2024-08-01 02:31:48,074: INFO server.static.router creating route for /home/acunetix/.acunetix/v_240626115/vue-ui (base path /app) 2024-08-01 02:31:48,107: INFO server.static.router indexed 507 files 2024-08-01 02:31:48,107: INFO server.static.router skipped 0 files 2024-08-01 02:31:48,107: INFO server.static.router creating route for /home/acunetix/.acunetix/v_240626115/ui (base path None) 2024-08-01 02:31:48,125: INFO server.static.router indexed 130 files 2024-08-01 02:31:48,125: INFO server.static.router skipped 0 files 2024-08-01 02:31:48,125: INFO server.application server application initialized 2024-08-01 02:31:48,390: INFO service.master starting the http server 2024-08-01 02:31:48,396: INFO service.master starting the reporter 2024-08-01 02:31:48,396: INFO service.master reporter worker started 2024-08-01 02:31:48,397: INFO reporter wvs_basedir /home/acunetix/.acunetix/v_240626115/scanner 2024-08-01 02:31:48,397: INFO reporter searching for pdf generator... 2024-08-01 02:31:48,397: INFO reporter trying /home/acunetix/.acunetix/v_240626115/scanner/pdf 2024-08-01 02:31:48,397: INFO reporter trying /home/acunetix/.acunetix/v_240626115/scanner/pdf.exe 2024-08-01 02:31:48,398: INFO reporter trying /home/acunetix/.acunetix/v_240626115/scanner/node 2024-08-01 02:31:48,398: INFO reporter pdf_converter=['/home/acunetix/.acunetix/v_240626115/scanner/node', 'pdf'] 2024-08-01 02:31:48,399: INFO service.master starting the system updater 2024-08-01 02:31:48,400: INFO helpers.updater update thread started 2024-08-01 02:31:48,400: INFO service.master starting the acumonitor thread 2024-08-01 02:31:48,402: INFO service.master starting the mailer thread 2024-08-01 02:31:48,402: INFO service.master starting lsr worker thread 2024-08-01 02:31:48,404: INFO service.master worker_checker started 2024-08-01 02:31:48,460: INFO xfqdn start fqdn processing for 986ad8c0a5b3df4d7028d5f3c06e936c 2024-08-01 02:31:48,475: WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c4011f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/DeleteTargets 2024-08-01 02:31:48,477: WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c400fe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/DeleteTargets 2024-08-01 02:31:48,477: WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c401e80>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/DeleteTargets 2024-08-01 02:31:48,478: ERROR xfqdn migration request failed with HTTPSConnectionPool(host='erp.acunetix.com', port=443): Max retries exceeded with url: /TargetManagement/Targets/DeleteTargets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c402030>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last): File "urllib3/connection.py", line 196, in _new_conn File "urllib3/util/connection.py", line 85, in create_connection File "urllib3/util/connection.py", line 73, in create_connection File "gevent/_socketcommon.py", line 590, in connect File "gevent/_socketcommon.py", line 634, in _internal_connect ConnectionRefusedError: [Errno 111] Connection refused
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "urllib3/connectionpool.py", line 789, in urlopen File "urllib3/connectionpool.py", line 490, in _make_request File "urllib3/connectionpool.py", line 466, in _make_request File "urllib3/connectionpool.py", line 1095, in _validate_conn File "urllib3/connection.py", line 615, in connect File "urllib3/connection.py", line 211, in _new_conn urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fe02c402030>: Failed to establish a new connection: [Errno 111] Connection refused
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "helpers/licensing/targets/fqdn.py", line 1073, in process_all_fqdn_by_owner_and_type File "helpers/licensing/targets/service.py", line 214, in uninstall File "helpers/licensing/targets/service.py", line 195, in do_request File "urllib3/_request_methods.py", line 144, in request File "urllib3/_request_methods.py", line 279, in request_encode_body File "urllib3/poolmanager.py", line 443, in urlopen File "urllib3/connectionpool.py", line 873, in urlopen File "urllib3/connectionpool.py", line 873, in urlopen File "urllib3/connectionpool.py", line 873, in urlopen File "urllib3/connectionpool.py", line 843, in urlopen File "urllib3/util/retry.py", line 519, in increment urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='erp.acunetix.com', port=443): Max retries exceeded with url: /TargetManagement/Targets/DeleteTargets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c402030>: Failed to establish a new connection: [Errno 111] Connection refused')) 2024-08-01 02:31:48,487: WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c403830>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/GetTargets 2024-08-01 02:31:48,489: WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c4183b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/GetTargets 2024-08-01 02:31:48,491: WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c418b60>: Failed to establish a new connection: [Errno 111] Connection refused')': /TargetManagement/Targets/GetTargets 2024-08-01 02:31:48,492: ERROR xfqdn error reaching target management service HTTPSConnectionPool(host='erp.acunetix.com', port=443): Max retries exceeded with url: /TargetManagement/Targets/GetTargets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c419250>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last): File "urllib3/connection.py", line 196, in _new_conn File "urllib3/util/connection.py", line 85, in create_connection File "urllib3/util/connection.py", line 73, in create_connection File "gevent/_socketcommon.py", line 590, in connect File "gevent/_socketcommon.py", line 634, in _internal_connect ConnectionRefusedError: [Errno 111] Connection refused
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "urllib3/connectionpool.py", line 789, in urlopen File "urllib3/connectionpool.py", line 490, in _make_request File "urllib3/connectionpool.py", line 466, in _make_request File "urllib3/connectionpool.py", line 1095, in _validate_conn File "urllib3/connection.py", line 615, in connect File "urllib3/connection.py", line 211, in _new_conn urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fe02c419250>: Failed to establish a new connection: [Errno 111] Connection refused
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "helpers/licensing/targets/fqdn.py", line 1101, in process_all_fqdn_by_owner_and_type File "helpers/licensing/targets/service.py", line 259, in get_targets File "helpers/licensing/targets/service.py", line 195, in do_request File "urllib3/_request_methods.py", line 144, in request File "urllib3/_request_methods.py", line 279, in request_encode_body File "urllib3/poolmanager.py", line 443, in urlopen File "urllib3/connectionpool.py", line 873, in urlopen File "urllib3/connectionpool.py", line 873, in urlopen File "urllib3/connectionpool.py", line 873, in urlopen File "urllib3/connectionpool.py", line 843, in urlopen File "urllib3/util/retry.py", line 519, in increment urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='erp.acunetix.com', port=443): Max retries exceeded with url: /TargetManagement/Targets/GetTargets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe02c419250>: Failed to establish a new connection: [Errno 111] Connection refused')) 2024-08-01 02:31:48,494: INFO xfqdn end fqdn processing for 986ad8c0a5b3df4d7028d5f3c06e936c 2024-08-01 02:31:48,500: INFO helpers.licensing re-activating 2024-08-01 02:31:49,015: INFO application.init Vtypes updated in 1.0014197549999153 seconds 2024-08-01 02:31:49,405: INFO service.master system init completed. 2024-08-01 02:31:49,407: INFO service.master Platform: Linux,Ubuntu 18.04.6 LTS,5.14.0-427.13.1.el9_4.x86_64,2.27

docker run -it -d -p 13443:3443 0xgkd/awvs执行完后，贴一下docker container ls命令的执行结果，还有uname -a的执行结果
